name: Build LLVM/CLANG as shared library on Windows (above)
on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

permissions:
  contents: read

jobs:
  build-main:
    name: Windows-LLVM-Shared-Library
    runs-on: windows-2025

    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      with:
        repository: mcbarton/llvm-project 
        path: ${{ github.workspace }}/llvm
        ref: a2223c497783ea7e535c2e8062ab832e73936c55

    - name: Setup default Build Type on Windows
      run: |
        $env:ncpus=$([Environment]::ProcessorCount) 
        echo "ncpus=$env:ncpus" >> $env:GITHUB_ENV

    - name: Setup compiler on Windows
      run: |
        $env:CC="clang-cl"
        $env:CXX="clang-cl"
        echo "CC=clang-cl" >> $env:GITHUB_ENV
        echo "CXX=clang-cl" >> $env:GITHUB_ENV

    - name: Install dependencies
      run: |
        choco install ninja

    - name: Build LLVM as a shared library on Windows
      run: |
        function Error-On-Failure {
          param (
              [Parameter(Mandatory)]
              [ScriptBlock]$Command
          )

         & $Command

         if ($LASTEXITCODE -ne 0) {
            exit $LASTEXITCODE
         }
        }
        cd ${{ github.workspace }}/llvm
        cmake -S ./llvm/ -B build -G Ninja                `
              -DCMAKE_ASM_MASM_FLAGS="-m64"     `
              -DLLVM_ENABLE_PROJECTS="clang"              `
              -DLLVM_ENABLE_PLUGINS=On                    `
              -DLLVM_TARGETS_TO_BUILD="host"              `
              -DCMAKE_BUILD_TYPE=RelWithDebInfo           `
              -DCMAKE_CXX_COMPILER=clang-cl               `
              -DCMAKE_C_COMPILER=clang-cl                 `
              -DCMAKE_ASM_MASM_COMPILER=llvm-ml           `
              -DLLVM_BUILD_LLVM_DYLIB_VIS=On              `
              -DLLVM_LINK_LLVM_DYLIB=On                   `
              -DCLANG_ENABLE_STATIC_ANALYZER=OFF                  `
              -DLLVM_INCLUDE_BENCHMARKS=OFF                    `
              -DLLVM_INCLUDE_EXAMPLES=OFF                      `
              -DLLVM_INCLUDE_TESTS=OFF                         `
              -DLLVM_BUILD_TOOLS=OFF                           `
              -DCLANG_BUILD_TOOLS=OFF                          `
              -DCLANG_LINK_CLANG_DYLIB=On                                 
        Error-On-Failure { cmake --build build --config RelWithDebInfo --parallel ${{ env.ncpus }} }
